name: guide_genie
description: A Flutter application for gamers to quickly access tier lists, loadouts, and strategies for popular games

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  
  # State management
  provider: ^6.1.4
  
  # HTTP and API
  http: ^1.3.0
  
  # Storage and Database
  shared_preferences: ^2.3.3
  sqflite: ^2.2.6
  path: ^1.8.2
  path_provider: ^2.0.15
  postgres_pool: ^2.1.5  # Compatible pool version
  flutter_dotenv: ^5.1.0
  
  # Math and Vectors (required by Flutter)
  vector_math: ^2.1.4
  
  # UI utilities
  cupertino_icons: ^1.0.5
  timeago: ^3.3.0
  flutter_svg: ^1.1.5
  url_launcher: ^6.1.6
  cached_network_image: ^3.3.1
  
  # Utilities
  uuid: ^3.0.6
  intl: ^0.17.0
  crypto: ^3.0.3
  google_fonts: ^6.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.1

flutter:
  uses-material-design: true
  
  assets:
    - .env
    - assets/
    - assets/app_logo.svg
    - assets/game_logos/fortnite.svg
    - assets/game_logos/league_of_legends.svg
    - assets/game_logos/valorant.svg
    - assets/game_logos/street_fighter.svg
    - assets/game_logos/call_of_duty.svg
    - assets/game_logos/warzone.svg
    - assets/game_logos/marvel_rivals.svg
  
  fonts:
    - family: Roboto
      fonts:
        - asset: fonts/Roboto-Regular.ttf
        - asset: fonts/Roboto-Bold.ttf
          weight: 700
        - asset: fonts/Roboto-Medium.ttf
          weight: 500
    - family: Audiowide
      fonts:
        - asset: fonts/Audiowide-Regular.ttf
