// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC7WnWJgTi1-wAEbBU4fPb3GPomeKXb5fs',
    appId: '1:580455826952:web:e72b6d33b663cbd24233bd',
    messagingSenderId: '580455826952',
    projectId: 'guidegenie-e672b',
    authDomain: 'guidegenie-e672b.firebaseapp.com',
    storageBucket: 'guidegenie-e672b.firebasestorage.app',
    measurementId: 'G-7EVY3SB0B9',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCbe9014a7O40hCGDtXxDMVL9AGLU2qs9g',
    appId: '1:580455826952:android:7f82ab22dc8d2b2d4233bd',
    messagingSenderId: '580455826952',
    projectId: 'guidegenie-e672b',
    storageBucket: 'guidegenie-e672b.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCqoEz7cCJmafc7wM08s7ol9en_Hr7SjYA',
    appId: '1:580455826952:ios:5b3ed5a61d87ad2d4233bd',
    messagingSenderId: '580455826952',
    projectId: 'guidegenie-e672b',
    storageBucket: 'guidegenie-e672b.firebasestorage.app',
    iosBundleId: 'com.example.workspace',
  );

}